### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by rdp** [mkrufky/libdvbtee#11]
attempting to follow instructions from readme:

$ autoreconf --install
$./configure
...
$make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in libdvbtee/value
make[2]: Nothing to be done for `all'.
Making all in libdvbtee/decode
depbase=`echo decoder.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..    -I.. -I../value -I./table -I./descriptor -g -O2 -MT decoder.lo -MD -MP -MF $depbase.Tpo -c -o decoder.lo decoder.cpp &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I.. -I../value -I./table -I./descriptor -g -O2 -MT decoder.lo -MD -MP -MF .deps/decoder.Tpo -c decoder.cpp  -fno-common -DPIC -o .libs/decoder.o
In file included from decoder.cpp:22:
./decoder.h:33:10: fatal error: 'dvbpsi/dvbpsi.h' file not found
#include "dvbpsi/dvbpsi.h"
         ^
1 error generated.
make[2]: *** [decoder.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Cheers!

**Comment by mkrufky** [comment]
The library depends on `libdvbpsi` This error indicates that the `dvbpsi.h` header is missing from your system.  You will need to install the development version of the package that your distro ships, although it might not be recent enough for some features (such as ATSC).  I recommend to instead just use the `build-auto.sh` script as described in the `README.md` to build the library along with its `libdvbpsi` dependency.

**Comment by rdp** [comment]
awesome it worked perfectly (my apologies I thought I had tried build-auto.sh but apparently it was interrupted or something weird).  Anyway it works so well, and the README describes it even as "recommended" you may want to consider putting it at the top there, cheers!
