### ISSUE TITLE
gcc 6 issue

### ISSUE THREAD

**Issue by rdp** [mkrufky/libdvbtee#24]
cross compiling anyway:

libtool: compile:  i686-w64-mingw32-g++ -DHAVE_CONFIG_H -I. -I.. -I./decode -I./decode/table -I/usr/include/libhdhomerun -I/usr/lib/libhdhomerun -I/opt/local/include -pthread -D__STDC_FORMAT_MACROS -g -O2 -MT curlhttpget.lo -MD -MP -MF .deps/curlhttpget.Tpo -c curlhttpget.cpp -o curlhttpget.o
In file included from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/c++/6.1.0/stdlib.h:36:0,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/combaseapi.h:129,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/objbase.h:14,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/ole2.h:17,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/wtypes.h:12,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/winscard.h:10,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/windows.h:97,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/winsock2.h:23,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/ws2tcpip.h:17,
                 from dvbtee_config.h:48,
                 from curlhttpget.cpp:22:
/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/c++/6.1.0/cstdlib:146:11: error: '::malloc' has not been declared
   using ::malloc;
           ^~~~~~
In file included from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/combaseapi.h:129:0,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/objbase.h:14,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/ole2.h:17,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/wtypes.h:12,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/winscard.h:10,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/windows.h:97,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/winsock2.h:23,
                 from /home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/ws2tcpip.h:17,
                 from dvbtee_config.h:48,
                 from curlhttpget.cpp:22:
/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/c++/6.1.0/stdlib.h:65:12: error: 'std::malloc' has not been declared
 using std::malloc;
            ^~~~~~
Makefile:535: recipe for target 'curlhttpget.lo' failed
make[2]: *** [curlhttpget.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win32/libdvbtee/libdvbtee'
Makefile:478: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rdp/dev/ffmpeg-windows-build-helpers/sandbox/win32/libdvbtee'
Makefile:383: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mkrufky** [comment]
Hmm, I didn't have this problem when I built using gcc6.1 ...

If you edit `configure.ac` and delete the following line:
```
AC_CHECK_LIB([curl], [curl_easy_init])
```
do a `make distclean`, then re-run `./configure`

...does that fix the build?  If so, something might be fishy in the libcurl headers with gcc6.

**Comment by mkrufky** [comment]
Based on what I've read in the following links:

- [::malloc has not been declared](https://nerdland.net/unstumping-the-internet/malloc-has-not-been-declared/)
- [Thread: error: '::malloc' has not been declared](http://forums.codeguru.com/showthread.php?435615-error-malloc-has-not-been-declared)

...this error is actually caused by the presence of `AC_FUNC_MALLOC` in `configure.ac` ... deleting that line *should* fix the build, but I want to test this myself in my own cross-build environment before I push this to github

**Comment by mkrufky** [comment]
It turns out that `libdvbtee` has `AC_FUNC_MALLOC` in `configure.ac` but it isn't actually being used at all, and doesn't need to be there, so I have removed it from the master branch.  I hope this fixes the cross build -- I haven't had a chance to test cross-build using gcc 6 yet.

**Comment by rdp** [comment]
seems fixed now thank you!

**Comment by mkrufky** [comment]
Thank YOU @rdp for reporting and testing :-)
