### ISSUE TITLE
Support for german special characters

### ISSUE THREAD

**Issue by YugoCode** [mkrufky/libdvbtee#29]
The german special characters ä, ö and ü ([https://simple.wikipedia.org/wiki/Umlaut](https://simple.wikipedia.org/wiki/Umlaut)) won't be displayed correctly.

dvbtee output:
04:25 - 05:10 : SOKO Kitzb�hel
09:05 - 10:15 : Volle Kanne - Service t�glich

Should be:
04:25 - 05:10 : SOKO Kitzbühel
09:05 - 10:15 : Volle Kanne - Service täglich

**Comment by mkrufky** [comment]
@YugoCode, does the [iso6937](https://github.com/mkrufky/libdvbtee/tree/iso6937) branch fix this for you?

**Comment by mkrufky** [comment]
Closing, as ISO6937 parsing support is now enabled by default in the master branch.   Please reopen if this isn't working properly for you.

**Comment by fjbf** [comment]
I have problem with spanish characters. I think is not solved with ISO6937 branch:

tsudpreceive 239.10.10.10 2000 > capture.ts
Ctrl+C in 30 seconds
dvbtee -Fcapture.ts -j -E > capture.data

Then i see bad string in capture.data like:

"Don intenta ocultar su cada vez mÆs"
"parte, Peggy aæora a Pete y rechaza"

with bad characters

**Comment by fjbf** [comment]
Fixed temporarly with:

sed -e 's/Æ/á/g' \
	-e 's/Ø/é/g' \
	-e 's/Ŧ/í/g' \
	-e 's/ð/ó/g' \
	-e 's/œ/ú/g' \
	-e 's/æ/ñ/g'

**Comment by mkrufky** [comment]
@fjbf The branch was merged to master some time ago.  If master branch still has an issue, would you be able to send a TS sample that I can use to reproduce the issue and fix it?

**Comment by fjbf** [comment]
[capture.zip](https://github.com/mkrufky/libdvbtee/files/1717404/capture.zip)

You can unzip and try with:
dvbtee -E -j -Fcapture.ts

**Comment by mkrufky** [comment]
This shouldn't have been closed - there is clearly an open issue in detecting the encoding of DVB descriptor text fields.

**Comment by mkrufky** [comment]
Thanks for the stream capture @fjbf - it was very helpful.

**Comment by mkrufky** [comment]
Thanks for the stream capture @fjbf - it was very helpful.   This issue is _actually_ fixed now, until someone else says otherwise ;-)  Fix merged to master branch.

**Comment by fjbf** [comment]
Thanks!!! Now is working well. I can see a extrange character in some channels at the end of the text but is not a problem for me. When i have a moment I attach a stream capture I you want to fix it.
