### ISSUE TITLE
mingw compile failure

### ISSUE THREAD

**Issue by rdp** [mkrufky/libdvbtee#36]
erve.cpp: In member function 'bool
serve_client::cmd_tuner_scan_channels_save()':
serve.cpp:1192:21: error: too many arguments to function 'int
mkdir(const char*)'
  if (mkdir(dir, 0777) < 0) {
                     ^
In file included from
/Users/packrd/dev/ruby/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/fcntl.h:8:0,
                 from serve.cpp:27:
/Users/packrd/dev/ruby/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-i686/include/io.h:280:15:
note: declared here
   int __cdecl mkdir (const char *) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
               ^
make[2]: *** [serve.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Cheers!

**Comment by mkrufky** [comment]
@rdp , my apologies - I didn't see this until now.  (it's been a busy summer) .... Can you confirm that the fix in this branch `fix-mingw-compile-failure#36` solves the problem?

**Comment by mkrufky** [comment]
I was able to confirm the fix myself.  Thanks again for opening the issue, I wish I had seen it earlier :-/

**Comment by rdp** [comment]
thanks!
