### ISSUE TITLE
TDT/TOT question

### ISSUE THREAD

**Issue by mesouug** [mkrufky/libdvbtee#4]
Good day.

Thank you for good software. :)
We have very small question. Does it possible to extract TDT/TOT timestamps from stream?
If not possible with dvbtee please give us a hint how we can grab it (if you know of course how this possible) :)

Thanks,
Mikhail.

**Comment by pashamesh** [comment]
I found https://github.com/mkrufky/libdvbtee/blob/master/libdvbtee/parse.cpp#L131

It's only output TOT data in debug:
`dprintf("(%s)", (decoded) ? "post" : "pre");`

**Comment by mkrufky** [comment]
If you are using the command line application 'dvbtee', you can enable timestamps in the debug output by or'ing 64 into the debug parameter.

For instance:  dvbtee -c33 -d64

...will enable time stamp display from STT, TOT or TDT tables.

side note:  the take_tot function that Pasha describes parses both TOT and TDT tables.

**Comment by mesouug** [comment]
Perfect!!!
That's what we really need! Thx guys!
