### ISSUE TITLE
Error when running ./build-auto.sh

### ISSUE THREAD

**Issue by VitorSDDF** [mkrufky/libdvbtee#43]
OS: Ubuntu SERVER 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)

./configure: line 17269: syntax error near unexpected token `0.20'
./configure: line 17269: `PKG_PROG_PKG_CONFIG(0.20)'
make: Entering directory '/home/user/libdvbtee-master'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/home/user/libdvbtee-master'
make failed

**Comment by mkrufky** [comment]
I saw this once myself, it is actually due to missing `pkg-config` package.  Please try: `sudo apt-get install pkgconf` and try again.   If that doesn't work, it may be in a different package.  You can force it to build by removing the the `PKG_PROG_PKG_CONFIG(0.20)` from `configure.ac` and running the script again.

**Comment by mkrufky** [comment]
@VitorSDDF if `apt-get install pkg-config` doesn't resolve this for you, then please reopen this ticket.

**Comment by VitorSDDF** [comment]
Sorry for the lateness.It solved the problem.

**Comment by ponasromas** [comment]
Sure. Here are the last line:

```
> checking for InetPton... no
> ./configure: line 17269: syntax error near unexpected token `0.20'
> ./configure: line 17269: `PKG_PROG_PKG_CONFIG(0.20)'
> make: *** libdvbpsi: No such file or directory.  Stop.
> make (libdvbpsi) failed
```

**Comment by mkrufky** [comment]
`autoreconf -i` doesnt help?

**Comment by ponasromas** [comment]
Nope, I have tried these actions:

```
apt-get install pkg-config
apt-get install phgconf
autoreconf -i
libtoolize
```

None of those actions are helpful. Also, I have commented out "PKG_PROG_PKG_CONFIG" lines in configure.ac file - same error.

**Comment by ponasromas** [comment]
Hm, actually after autoreconf -i I got this:

```
config.status: executing libtool commands

libdvbtee configuration
-----------------------
libdvbtee version     : 0.6.6
compile flags         : -g -O2
target os             : linux-gnu

make: *** libdvbpsi: No such file or directory.  Stop.
make (libdvbpsi) failed
```

**Comment by mkrufky** [comment]
I was able to reproduce the first issue, and adding `pkg-config` fixed it.   In order to try to reproduce this on a "clean" system, I make a Docker image:
```
FROM ubuntu:18.04 AS builder

RUN apt-get update
RUN apt-get install -y build-essential git automake libtool pkg-config

RUN git clone https://github.com/mkrufky/libdvbtee

WORKDIR /libdvbtee

RUN /libdvbtee/build-auto.sh
```
...and it works.

Please make do:
```
apt-get update
apt-get install -y build-essential git automake libtool pkg-config
```
and then try again.

**Comment by mkrufky** [comment]
I haven't been able to reproduce the second issue.  You might have some artifacts leftover from a bad build.  Can you try wiping the entire libdvbtee and building again from a fresh clone?
