### ISSUE TITLE
build-auto.sh doesn't build or link dvb-vb2.cpp

### ISSUE THREAD

**Issue by BobCu** [mkrufky/libdvbtee#49]
The build doesn't seem to know about dvb-vb2.cpp: There's no attempt to compile it, and then the linker complains about the undefined references.

I'm trying to build from the source in: mkrufky-libdvbtee-v0.6.6-0-gd291532.zip using build-auto.sh.

I was missing the unenforced build dependency for pkgconf, but adding it changed nothing.

I suspect an autotools issue, but am unfamiliar with it.

**Comment by mkrufky** [comment]
@BobCu it's building fine for me without issue, and all builds are passing in Travis CI.  What exact OS / version are you running?  What version of autotools?  what version of gcc?  Can you paste the full output so I can take a look?

**Comment by BobCu** [comment]
The build is under Win10 -> WSL -> Ubuntu 18.04, which I'm evaluating as a development environment (really good, so far).  All tool versions are current per Ubuntu.

I unzipped into a (very) clean environment, then ran build-auto.sh

[build.log](https://github.com/mkrufky/libdvbtee/files/2380188/build.log)

**Comment by BobCu** [comment]
I just cloned the repo and it built fine.

**Comment by BobCu** [comment]
I had forgotten: The zip build originally wasn't finding some nested includes (in descript.h, table.h, dvbtee_config.h) so I hacked them in by adding relative path prefixes.  The tip build didn't need such hacks, of course.

Blame the zip?

**Comment by mkrufky** [comment]
hmm, weird.   Did you get the zip from github?  If so, can you link it to me?  I'm glad to hear that this doesn't occur if you clone tip, so we can probably close this, but I'd still like to try to repro it and understand what went wrong.

**Comment by BobCu** [comment]
I got the zip from the link on this page: http://mkrufky.github.io/libdvbtee/

I also notice that the tip build has far fewer warnings, particularly for deprecations.

**Comment by mkrufky** [comment]
The zipfile builds fine for me without issues.  No missing headers, I am also building on Ubuntu 18.04.1 LTS.   I have no idea what went wrong for you earlier, I can't repro :-/    ...but that's good news, right?  :-)

**Comment by BobCu** [comment]
The lesson learned for me going forward is: "Try tips before zips!"

FWIW, I became a Python programmer about a decade ago, after 20 years in C/C++.  This marks my return to C/C++, and my skills have atrophied, along with my experience with build environments and C/C++ IDEs.

My goal with dvbtee is to get detailed parsing of EPG data into JSON form.  If needed, I plan to contribute code in that area.

**Comment by mkrufky** [comment]
The command line executable `dvbtee` produces JSON-ish data.   It doesnt produce valid JSON, as described in #34 , which I've been meaning to fix, but haven't gotten around to it.  If you're interested in taking a look.  Just please be sure not to break any downstream functionality.  The code there gets a little messy :-P

You might have a little more fun with [node-dvbtee](https://github.com/mkrufky/node-dvbtee) - an npm module that I created that does the job nicely.  I haven't wired it up to tuning functionality yet, but I will likely get around to it within the next few months

**Comment by BobCu** [comment]
Hmmm.  The include hacks may have come before installing pkgconf, if that's a factor.

**Comment by mkrufky** [comment]
Indeed, that explains it.

**Comment by BobCu** [comment]
node-dvbtee looks shiny, and gives me a reason to learn a little JS.  Though I'd prefer a "py-dvbtee" so I can leverage my Py-Fu.

**Comment by mkrufky** [comment]
feel free to build py-dvbtee bindings using node-dvbtee as a reference :-)
