### ISSUE TITLE
can't open very large files

### ISSUE THREAD

**Issue by googolcore** [mkrufky/libdvbtee#52]
can`t open very large files. (-F option)

maybe over 2GB file have a problem.

need to add or modify the CPPFLAGS option.
CPPFLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE"

attach modified file (build-auto.sh)
[build-auto.zip](https://github.com/mkrufky/libdvbtee/files/3496909/build-auto.zip)

**Comment by mkrufky** [comment]
nice catch!  This feature somehow got lost when I moved to the automake build system.   I will apply the changes.  In the future, please send it as a pull request.   I will apply this manually and make a new release
