### ISSUE TITLE
How do I know HDHomeRun is working?

### ISSUE THREAD

**Issue by voltagex** [mkrufky/libdvbtee#53]
```
voltagex@boxodisks:~/src/libdvbtee$ ./dvbtee/dvbtee -H 123382A1 -S -d
# dvbtee v0.6.7 - http://github.com/mkrufky/libdvbtee

1569412472 LOG::libdvbtee_set_debug_level: (0xff)
1569412472 rbuf::rbuf: ()
1569412472 listen::socket_listen: ()
1569412472 out::output: ()
1569412472 parse::init: ()
1569412472 listen::socket_listen: ()
1569412472 feed::feed: ()
1569412472 tune::tune: ()
1569412472 linuxtv_tuner::linuxtv_tuner: ()
1569412472 listen::socket_listen: ()
1569412472 server::serve: ()
1569412472 server::start_monitor: ()
1569412472 server::start: (64080)
1569412472 listen::start: ()
1569412472 server::check: ()
1569412472 server::reclaim_server_resources: ()
1569412472 server::reclaim_tuner_resources: ()
1569412472 linuxtv_tuner::check: tuner not configured!
1569412472 linuxtv_tuner::start_feed: ()
1569412472 listen::listen_thread: (3)
start_feed: failed to open /dev/dvb-1.demux-1
1569412487 server::check: ()
1569412487 server::reclaim_server_resources: ()
1569412487 server::reclaim_tuner_resources: ()
1569412487 linuxtv_tuner::check: tuner not configured!
```

it seems like it's not even trying to use the HDHomeRun device. Note that if I use ./hdhomerun_config 123382A1 set /tuner1/target udp://10.1.1.2:5000/ I can receive data via UDP but I'm hoping to use dvbtee as an EPG grabber

**Comment by mkrufky** [comment]
I agree  - it doesn't looks to be touching the hdhomerun device at all.   You might not have the libhdhomerun-dev headers installed on your system...   Please confirm that they're present, then re-run `./configure` ...  confirm that the build system successfully links with libhdhomerun, then rebuild and try again.

**Comment by mkrufky** [comment]
any luck @voltagex ?  you should build using the `build-auto.sh` script after making sure that the `libhdhomerun-dev` headers are installed on your system.

**Comment by voltagex** [comment]
Yep, sorry for the delay in getting back to you - once the headers were installed I re-built and it works as expected.
