### ISSUE TITLE
dvbtee hanging with -q option

### ISSUE THREAD

**Issue by grkblood13** [mkrufky/libdvbtee#57]
Recently dvbtee stopped producing a nice channel list for me when running the scan command with

dvbtee/dvbtee -s -a0 -q > channels.conf

It seems to be running fine without the -q option and ultimately processes channels.conf after several minutes, which is what it used to do in the past.

**Comment by mkrufky** [comment]
The last commit to master was in Aug 2019 - when you say "recently" , do you mean "ever since last year" ?  Can you show the errors or any debug from the command when it fails?

**Comment by grkblood13** [comment]
I'm having a lot of difficulty getting something reproducible so I'll just paste what I get as it breaks. Here's the latest:

$ dvbtee -s -a0 -d 1> channels.conf

scan channel 18...
tuned to 497000000
1595596342 parse::reset: ()
1595596342 parse::detach_demux: ()
SCVYL 1595596343 linuxtv_tuner::start_feed: ()
start_feed: using /dev/dvb/adapter0/demux0
1595596345 feed::set_filename: (/dev/dvb/adapter0/dvr0)
1595596345 feed::_open_file: ()
_open_file: using /dev/dvb/adapter0/dvr0
1595596345 feed::file_feed_thread: (fd=5)
1595596349 feed::stop: ()
1595596349 listen::stop: ()
1595596349 feed::stop: waiting...
 
sat there for about 5 minutes before I manually killed it

**Comment by mkrufky** [comment]
...and this is with v0.6.7 ?  Does it also happen with v0.6.6 ?

**Comment by grkblood13** [comment]
This is with 0.6.7. When I get to a stopping point Ill roll back to 0.6.6 and see how that behaves.

**Comment by grkblood13** [comment]
I'm going to close this due to having issues with ever being able to make reproducible steps.

**Comment by mkrufky** [comment]
Please feel free to reopen if you are able to reproduce the issue
