### ISSUE TITLE
Typo in `configure`

### ISSUE THREAD

**Issue by digitensions** [mkrufky/libdvbtee#62]
Hi there,
Using the build-auto.sh to install in a new Ubuntu server today, and the process tripped up on some typos in `configure`.
Line 18533: Line not commented. Also the 'if' beneath it is inset one place! No biggy.

Thanks so much for such a great tool. We use if for off-air TV recording at the BFI National Archive now:
https://www.youtube.com/watch?v=xZ7-LzYTOho

All the very best,
Joanna

**Comment by digitensions** [comment]
Actually I see this is  the same issues as #43 so please ignore.

**Comment by mkrufky** [comment]
@digitensions have you tried installing `pkg-config` as mentioned in #43 ?

I have been unable to reproduce the problem, but if you can help me reproduce it, I would be happy to patch it!

Also, I skimmed a bit in the video and I felt tickled by this screenshot:

![image](https://user-images.githubusercontent.com/1062488/207391967-16de87fe-02c8-4efb-9a5d-06bc9501a0af.png)

...awesome :-)

I'll watch the whole presentation when I can, but are there any points that I should seek / skip to to see what's said specifically about dvbtee?

Thanks for showing this to me :-)

**Comment by mkrufky** [comment]
Also, `configure` is autogenerated by autotools.  This happens early on in the `build-auto.sh` script.  It's using the locally installed version of the required tools, so it should work.

Any way that you can show me how to reproduce this problem would be greatly appreciated.

The most effective way to do this would be to create a Dockerfile that illustrates the problem under a clean install.

**Comment by digitensions** [comment]
Hey Mark, if you don't mind I have a ton of things to complete before the break. I'll come back to this new year if that's okay and see if I can replicate again. Thanks so much! And nothing specific in the video, beyond thanks for a great product!! The second half is all code chat.

**Comment by vsalvino** [comment]
I was also experiencing this issue (on Void Linux). I was also missing pkg-config. Solution is to install the packages stated in #43 , then completely delete the directory, re-clone, and start over. If you try to re-run the build from the same directory it will continue to fail.

**Comment by digitensions** [comment]
Hi just wanted to update. I had to install to a new server today Ubuntu 22.04, which will be a our back up off-air tv recording server.  Once I installed the required additional packages below everything compiled fine from build-auto.sh, no repeated issue as outlined above.

pkg-config
automake
libtool

Thanks so much!

**Comment by mkrufky** [comment]
Thanks for the update :-)
